print:
	## Prints to names Print. No dialog.
	lpr -P printername pdf-test.pdf

print1:
	## Prints to default. No dialog.
	lpr  pdf-test.pdf

preview:
	## OS X's Preview app, and then use can pritn from there !!
	# Works !! This it.
	open pdf-test.pdf

win-preview:
	# Does it have one ?
	# https://stackoverflow.com/questions/6557920/how-to-open-a-pdf-in-fullscreen-view-via-command-line
	# Need to test each.
	

